### ISSUE TITLE
Missing help text to new grading type options "Longest ordered subset" and "Longest contiguous subset"

### ISSUE THREAD

**Issue by Kathrin84** [gbateson/moodle-qtype_ordering#10]
Hi,

with your latest version 2016-01-23-(40) you added the two new grading types "Longest ordered subset" and "Longest contiguous subset". Unfortunately there's no help text to those new types.
Could you add such a help text?

Thanks and cheers,
Kathrin

**Comment by gbateson** [comment]
Hmm, the new grading types have help available so I wonder why you cannot see them?
Next to the "Grading type" item you should see a help icon, which, if you click, will reveal the help text inserted below. Can you see the help icon? Can you see the help text? It is definitely there. Her it is on github.com:
https://github.com/gbateson/moodle-qtype_ordering/blob/master/lang/en/qtype_ordering.php
=================================
Choose the type of grading calculation.

**Absolute position**
An item is considered correct if it is in the same position as in the correct answer. The highest possible score for the question is the same as the number of items displayed to the student.
**Relative to the next item (excluding last)**
An item is considered correct if it is followed by the same item as it is in the correct answer. The item in the last position is not checked. Thus, the highest possible score for the question is one less than the number of items displayed to the student.
**Relative to the next item (including last)**
An item is considered correct if it is followed by the same item as it is in the correct answer. This includes the last item which must have no item following it. Thus, the highest possible score for the question is the same as the number of items displayed to the student.
**Relative to both the previous and next items**
An item is considered correct if both the previous and next items are the same as they are in the correct answer. The first item should have no previous item, and the last item should have no next item. Thus, there are two possible points for each item, and the highest possible score for the question is twice the number of items displayed to the student.
**Relative to ALL previous and next items**
An item is considered correct if it is preceded by all the same items as it is in the correct answer, and it is followed by all the same items as it is in the correct answer. The order of the previous items does not matter, and nor does the order of the following items. Thus, if n items are displayed to the student, the number of marks available for each item is (n - 1), and the highest mark availabe for the question is n x (n - 1), which is the same as (n² - n).
**Longest ordered subset**
The grade is the number of items in the longest ordered subset of items. The highest possible grade is the same as the number of items displayed. A subset must have at least two items. Subsets do not need to start at the first item (but they can) and they do not need to be contiguous (but they can be). Where there are multiple subsets of equal length, items in the subset that is found first, when searching from left to right, will be displayed as correct. Other items will be marked as incorrect.
**Longest contiguous subset**
The grade is the number of items in the longest contiguous subset of items. The highest possible grade is the same as the number of items displayed. A subset must have at least two items. Subsets do not need to start at the first item (but they can) and they MUST BE CONTIGUOUS. Where there are multiple subsets of equal length, items in the subset that is found first, when searching from left to right, will be displayed as correct. Other items will be marked as incorrect.
=================================

**Comment by Kathrin84** [comment]
Sorry, now I see that it was my mistake. I did the translation in Amos and did not see that there was an addition to the help text. And then within the plugin I had German active, so I did not see the additional text at all. 
I'll complete the german translation and everything is fine then. You can close this ticket and sorry for the inconveniences!

Cheers,
Kathrin

**Comment by gbateson** [comment]
Tanks for translating into German Kathrin. Keep up the great work ! regards, Gordon
