### ISSUE TITLE
Export / import attached files to xml

### ISSUE THREAD

**Issue by vadimonus** [gbateson/moodle-qtype_ordering#12]
Currently we use other question type for ordering questions, but your plugin looks better. But we need to use pictures into the answers. I have found that i can add them and all works great. But when i try to export questions into moodlexml and reimport them, i found that pictures are not saved and code does not contain commands for exporting attached files.

**Comment by vadimonus** [comment]
I can make such improvements, but i need to know that you are intrested in them before i start working.

**Comment by gbateson** [comment]
Hi Vadim, sounds interesting. Please proceed and I will include the new code.

BTW, I have also create a tool to convert qtype_order questions to qtype_ordering. Perhaps it will help you: https://github.com/gbateson/moodle-tool_qtypeorder

**Comment by gbateson** [comment]
Vadim, thanks again for your improvements to the Ordering question type. I have merged them into the master branch and made the new release available on moodle.org. best regards, Gordon
