### ISSUE TITLE
Default edit mode for questions

### ISSUE THREAD

**Issue by vadimonus** [gbateson/moodle-qtype_ordering#13]
Currently we use other question type for ordering questions, but your plugin looks better. But we need to use pictures into the answers. To add pictures we need create question, save it, add some more fields, insert something into fields for answers (if fields are empty, they do not remember selected editor), switch mode for every answer to html editor, save question again, and only then we have ability to add pictures and formatting. It would be very useful to create setting for default editor.
I can make such improvements, but i need to know that you are intrested in them before i start working.

**Comment by gbateson** [comment]
Hi Vadim, I am interested in the improvement that you propose. Please proceed!

**Comment by gbateson** [comment]
Vadim, thanks again for your improvements to the Ordering question type. I have merged them into the master branch and made the new release available on moodle.org. best regards, Gordon
