### ISSUE TITLE
The question doesn't work with "Adaptive Mode"

### ISSUE THREAD

**Issue by yairbh** [gbateson/moodle-qtype_ordering#17]
In the quiz settings, when switching the behaviour of the questions to "Adaptive mode and Adaptive mode (no penalties)", it doesn't seem to affect the qtype_ordering question. It only allows answering once, with no option to change the answer (as opposed to questions of other types on the same quiz). 
Is there a way of solving this issue?

**Comment by gbateson** [comment]
Thanks yairbh!
I have improved the Ordering question type to behave as expected when the Quiz is in "Adaptive mode" or "Adaptive mode (no penalties)".

Please arrange for the Ordering question type on your Moodle site to be updated at the next convenient opportunity.

Best regards,
Gordon

**Comment by yairbh** [comment]
I'll try, thanks!
