### ISSUE TITLE
Images do not show up when student give wrong answers, in attempt review mode.

### ISSUE THREAD

**Issue by nadavkav** [gbateson/moodle-qtype_ordering#19]
Students can not see images in quiz review mode, when the answer is wrong or partially wrong. 
They do see the images without any issues while quiz attempt in progress. And also, when getting correct answers.
Looking at the image URL, I see the @@pluginfile@@ is not getting converted to a fully qualified Moodle URL.

Anyone experienced something weird like this?

**Comment by gbateson** [comment]
Hi Nadav, thanks for reporting this issue. It is fixed in the latest release of this plugin. Please arrange for the Ordering question type on your Moodle site to be updated at the next convenient opportunity. Regards, Gordon

**Comment by nadavkav** [comment]
Thanks!

**Comment by gbateson** [comment]
You're welcome. I'm closing this issue now. Please re-open it if you feel it is not yet fixed.
