### ISSUE TITLE
Ordering of options doesn't work on iOS devices

### ISSUE THREAD

**Issue by aspark21** [gbateson/moodle-qtype_ordering#20]
Moodle: 3.0
plugin version: 2016022445

Ordering of options doesn't work on iOS devices - can't drag& drop the options. Works fine on desktops.

**Comment by gbateson** [comment]
Please update your plugin.
Latest version is 2017-05-08 (59)

**Comment by aspark21** [comment]
Will do. Didn't see anything addressing that particular thing in the title of the commits in between those versions though.

**Comment by gbateson** [comment]
Latest version works fine on my iPhone.
Please let me know how you get on.

**Comment by aspark21** [comment]
ok will do. Thanks!

**Comment by aspark21** [comment]
Hi Gareth,

We upgraded to 2017040658 which is the latest master branch but this hasn't resolved the issue. Where is 59?

**Comment by gbateson** [comment]
59 is now available on the github site. However, it is not very different from (58) with regard to the basic ordering functionality.

What's theme and Moodle version are you using?

**Comment by aspark21** [comment]
We are Moodle 3.0.4 and using a customised version of the clean theme.

**Comment by gbateson** [comment]
On my Moodle 3.0.10 server with standard Clean theme, the Ordering questions work fine on iOS 10.3.2

**Comment by gbateson** [comment]
You can access the sample Quiz I created on the following URL:

- [Gordon Bateson development server](http://bateson.kochi-tech.ac.jp/30/course/view.php?id=2)
- Username: guestteacher
- Password: taskchainv09

The above quiz includes on Ordering question. 
It displays and behaves as expected on my iPhone.
Can you view it on your iOS device?

**Comment by aspark21** [comment]
Hi Gordon, managed to login but the guest teacher isn't enrolled on the course & can't self enrol.

**Comment by gbateson** [comment]
Sorry about that Alistair. I have enrolled the guestteacher and gueststudent users now. They both have the same password: taskchainv09

**Comment by gbateson** [comment]
Alistair, were you able to login to my testing server and check the performance of the Ordering questions on a iOS?

**Comment by gbateson** [comment]
Alistair,
I believe this issue is fixed by the latest version of the Ordering question type, which replaces jQuery sorting code with code from Moodle's standard Drag-and-Drop question types.
Please could you upgrade to the latest version of this plugin and verify that items are now draggable on your iOS device. Thanks.

**Comment by aspark21** [comment]
Hi Gordon,  
I will ask my ex-colleagues at the RVC to take a look & get back to you.

**Comment by gbateson** [comment]
Thanks Alistair.
I have not heard from RVC, so I will close this issue for now.
Feel free to re-open it, if the issue recurs for you or the RVC.
Many thanks,
Gordon
