### ISSUE TITLE
Lost results after updating to 3.3

### ISSUE THREAD

**Issue by zichichi** [gbateson/moodle-qtype_ordering#21]
Hi,
After updating to moodle version 3.3, quiz results are no longer displayed. I attach a screenshot.

https://ibb.co/gFcT7k

**Comment by gbateson** [comment]
Hello,
the results display for me on my Moodle 3.3 (see attached screenshot)

<img width="541" alt="ordering-on-moodle-3 3" src="https://user-images.githubusercontent.com/799312/27578898-8705eb24-5b60-11e7-9e80-2f63f5ba201d.png">

**Comment by gbateson** [comment]
FYI, my Moodle 3.3 site is using the standard "Clean" theme and version 2017-05-08 (59) of the Ordering question type.

**Comment by zichichi** [comment]
The problem occurs only with the old quizzes, if I try to make a new one work.

**Comment by gbateson** [comment]
Hi Zichichi,
Are you still experiencing this issue with the Ordering question type for Moodle?
I believe it is fixed with the latest release of this plugin. Please could you update and confirm?
Thanks.

**Comment by gbateson** [comment]
From my testing on Moodle 3.3 and later, in both Clean and Boost theme, the Ordering questions and answers are displayed, so I believe this issue is fixed, Therefore, I will close this issue now.
Please reopen it if you continue to experience problems.
Many thanks, Gordon
