### ISSUE TITLE
Does not work  on Moodle 3.6

### ISSUE THREAD

**Issue by Canx** [gbateson/moodle-qtype_ordering#26]
questions can't be reordered on Moodle 3.6 when answering the question.

edit: updated to master and also not working.

**Comment by gbateson** [comment]
Hmm, seems to work OK on my Moodle 3.6 🤔
Attached screenshot shows me dragging an item.
I'm using the the "Clean" theme. What theme are you using?

![moodle-3 6-ordering](https://user-images.githubusercontent.com/799312/48989949-cf840600-f16f-11e8-8e74-3eb1bf2425b0.png)

**Comment by germanvaleroelizondo** [comment]
It works well in Moodle 3.6rc1 (Build: 20181125).

![ordering qtype demo](https://user-images.githubusercontent.com/2671923/49037959-35c55480-f181-11e8-9cc8-75c5e0c8f7f4.png)

But the version hosted in the Moodle plugins database is older than the one in GitHub :(

**Comment by Canx** [comment]
Hi Gordon,

I re-tested the problem with Moodle 3.6rc1 (Boost theme) and the problem has vanished! 

So maybe the problem was Moodle prior to rc1... I go against Moodle recommendations and use Moodle master branch, I get some early features but also some nasty bugs!

**Comment by gbateson** [comment]
Thanks Canx and German, 
for confirming the the Ordering question is working fine in Moodle 3.6, including in the Boost theme.

Canx, this repository only has a Master branch, so you are quite right to use that.
FYI, the version of this plugin in the Moodle plugins repository is sometimes a little behind the version on Github.com. If you have a choice of where to download from, I recommend you use Github.com.

Best regards
Gordon
