### ISSUE TITLE
"Select a contiguous subset of items"

### ISSUE THREAD

**Issue by dbauer-ets** [gbateson/moodle-qtype_ordering#29]
Plugin Version: Version release name 2018-05-24 (69)
Moodle 3.4.2

Hello Gordon,

If you set "Item selection type" to "Select a contiguous subset of items",
set "Size of subset" to a value less than the total number of draggable items,
and set "Grading type" to any type,

then the number of items displayed to the student does not match the size of the chosen subset. In fact, it seems to be random. Is this really the desired behavior? I would think no.

**Comment by gbateson** [comment]
Hi Dominique,
Thanks for your report regarding the Ordering question type.
The behavior that you report is not the behavior that I see with release 2018-11-19 (73).

With 6 items available, if the subset size 4, then I see 4 items when the question is presented to the student, and if the subset size is 3, then I see 3 items. This is the expected and desired behavior.

Please could you reproduce your question and its errant behavior on my development server, and I will investigate.

- **URL:** https://bateson.kochi-tech.ac.jp/34/
- **Course:** Course Fullname 101
- **Username:** guestteacher
- **Password:** taskchainv09

**Comment by gbateson** [comment]
Hmm, sorry. I take that back.
As you say, there are problems when the "Item selection type" to "Select a contiguous subset of items". I'll investigate and report back.

**Comment by gbateson** [comment]
This issue is now fixed in the latest version of this plugin: 2018-11-26 (74)

Please arrange for this plugin to be updated on your Moodle server at the next convenient opportunity.
You are also welcome to confirm the new behavior on my development server, using the access details given earlier in this thread.

Many thanks for bring this issue to my attention.

**Comment by dbauer-ets** [comment]
I see that Release 2018-05-24 (69) is available at https://moodle.org/plugins/qtype_ordering. Is the latest version available on this repository?
