### ISSUE TITLE
DDL sql execution error during install

### ISSUE THREAD

**Issue by savedario** [gbateson/moodle-qtype_ordering#3]
I attempted to install the plugin directly from Moodle's site on my Moodle 2.8 installation and got this error:

Debug info: Key column 'question' doesn't exist in table
CREATE TABLE mdl_qtype_ordering_options (
id BIGINT(10) NOT NULL auto_increment,
questionid BIGINT(10) NOT NULL DEFAULT 0,
selecttype SMALLINT(4) NOT NULL DEFAULT 0,
selectcount SMALLINT(4) NOT NULL DEFAULT 0,
correctfeedback LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
correctfeedbackformat TINYINT(2) NOT NULL DEFAULT 0,
incorrectfeedback LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
incorrectfeedbackformat TINYINT(2) NOT NULL DEFAULT 0,
partiallycorrectfeedback LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
partiallycorrectfeedbackformat TINYINT(2) NOT NULL DEFAULT 0,
CONSTRAINT PRIMARY KEY (id)
, KEY mdl_qtypordeopti_que_ix (question)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE = utf8_general_ci
COMMENT='Options for ordering questions'
Error code: ddlexecuteerror

Stack trace:

    line 449 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
    line 905 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 76 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database->change_database_structure()
    line 412 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
    line 364 of /lib/ddl/database_manager.php: call to database_manager->install_from_xmldb_structure()
    line 500 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
    line 1626 of /lib/upgradelib.php: call to upgrade_plugins()
    line 434 of /admin/index.php: call to upgrade_noncore()

**Comment by gbateson** [comment]
Thank you very much for alerting me to this issue. I have modified the install.xml file which defines the indexes for this question type. Please delete the "mdl_qtype_ordering_options" table (if it exists) from your Moodle database and try the install again. regards, Gordon

**Comment by savedario** [comment]
Just to confirm:
The table was never created because of the error.
I copied install.xml and it worked. Thanks.
One more question:
Is the source of the Moddle built-in plugin installation coming directly from this repo or is there some updated process in the middle ?

**Comment by gbateson** [comment]
The Moodle.org zip file comes straight from the github.com repository. The github.com repository is always updated BEFORE the Moodle.org repository. all the best, Gordon
