### ISSUE TITLE
Identical draggable items

### ISSUE THREAD

**Issue by dbauer-ets** [gbateson/moodle-qtype_ordering#31]
Hello Gordon,

Can the following question, with identical items, work with Ordering?

![otherquestiontypes20181126-1343](https://user-images.githubusercontent.com/22897609/49036279-45df3300-f185-11e8-8644-06fe3db3cb18.png)

**Comment by gbateson** [comment]
Hi Dominque,
The Open University of the UK has recently added code to prevent duplicate items when adding/editing a new Ordering question. This new code will prevent issues such as the one your reported. Of course it will also prevent use using this plugin for spelling tests.

However, in the list of future improvements for this plugin, I have made a note  to allow not only duplicates, but also alternative orderings that have each has an associated grade.

I will close this issue for now.
