### ISSUE TITLE
How to upgrade from qtype_order 

### ISSUE THREAD

**Issue by danpospisil** [gbateson/moodle-qtype_ordering#33]
Hi,

we are still using the old qtype_order. Is there a way how to transfer everything to the new qtype_ordering? 

Thanks!

**Comment by gbateson** [comment]
Hi Dan,
Maybe this tool will help:
https://github.com/gbateson/moodle-tool_qtypeorder

I haven't tested it very recent versions of Moodle, so please proceed with caution.

If you need help getting it to run, please let me know.

**Comment by gbateson** [comment]
Hi Dan,
I'm closing this issue because I believe the "tool_qtypeorder" will migrate old "order" questions to new "ordering" questions as you desire.
Feel free to reopen the "tool_qtypeorder" tool does not answer you requirements.
