### ISSUE TITLE
Clicking "Add" to add items more than once without saving the question in between has incorrect and unwanted behavior

### ISSUE THREAD

**Issue by rlorenzo** [gbateson/moodle-qtype_ordering#35]
I have a bug report from one of our support staff:

Clicking "Add" to add items more than once without saving the question in between has incorrect and unwanted behavior. Items added after the first time "Add" is clicked have an HTML editor instead of the standard edit box. Clicking "Remove HTML Editor" at this point boots the user out of the question editor. (Tested on Windows 10, Google Chrome 71.0.3578.98 64-bit and Microsoft Edge 42.17134.1.0)

This is happening on version 2018-01-17 (68) and 2018-12-12-(77) of the plugin.

**Comment by gbateson** [comment]
Thanks for bringing this issue to my attention.
I think I have fixed it in today's release of the plugin: 2018-12-15 (78)
At the next convenient opportunity, please could you update the plugin on your Moodle site and confirm the fix.
