### ISSUE TITLE
Item reordering doesn't work when Browser Security is enabled

### ISSUE THREAD

**Issue by m-x-d** [gbateson/moodle-qtype_ordering#36]
Dragged answer becomes stuck in the "dragged" state when Browser security is enabled in the Test settings. Seems like mouseUp event fails to be processed for whatever reason. Works fine when Browser security is disabled.
Observed in the latest git release of the plugin (moodle-qtype_ordering-2018-12-21) in Moodle 3.6.1, using Firefox 64 and Firefox 52 ESR.

**Comment by m-x-d** [comment]
Works fine in Chrome and IE 11. Can't test in Safari (I have no access to a Mac or iPhone).
"Drag and drop into text" and "Drag and drop markers" question types seem to work fine in FF 64.

Commenting out "e.halt();" line in M.mod_quiz.secure_window prevent_mouse function in "moodle\mod\quiz\module.js" fixes the issue in FF, but obviously that's not the proper solution.

**Comment by m-x-d** [comment]
Adding "self.element.contenteditable = true;" line to mouseProto._mouseInit function in "ordering\amd\src\jquery.ui.touch-punch-improved.js" also fixes the issue in FF.

**Comment by m-x-d** [comment]
Adding 'contenteditable' => 'true' attribute to the [ul tag](https://github.com/gbateson/moodle-qtype_ordering/blob/e1574f760f4ea700867b8b91632187015f80a7b6/renderer.php#L149) housing answer items also seems to fix the issue in FF.

**Comment by gbateson** [comment]
I see. Nice detective work - and fast!!
Does the ul tag have a "class" attribute that includes "sortablelist"?
If so, we can fix this quite easily. Please could you confirm the "class" of the ul tag.

**Comment by m-x-d** [comment]
It does: `<ul class="sortablelist ui-sortable" id="id_sortable_341711">`

**Comment by gbateson** [comment]
I tried Firefox 64 on Mac and I don't see the behavior your report 🤔
You mentioned you were using Moodle 3.6. Which theme are you using?

**Comment by m-x-d** [comment]
The default Boost theme.
I'm using Moodle 3.6.1.
Are you sure you are launching the test using a Student role (it should open in a separate window with reduced controls)? It works fine when launched as an admin or teacher on my side.

**Comment by gbateson** [comment]
Thanks for the clarification. I'll try Boost theme logged in as a student ...

**Comment by gbateson** [comment]
I was able to replicate the behavior in Firefox using Boost theme, logged in as a student on Moodle 3.6.
I added contenteditable="true" to the main UL list, which has class="sortablelist", and confirmed the behavior is rectified in Firefox 64 on Mac. I checked Safari and Chrome on Mac and they also behave as expected with the modification.
Therefore, I will commit this change to the public release. 
Many thanks for reporting this issue, investigating the conditions and suggesting the fix 👍

**Comment by gbateson** [comment]
I have added this modification to the latest public release.
Please arrange for this plugin to be updated on your Moodle site, and confirm that draggable items no longer become stuck to the cursor when logged in as a student on Moodle 3.6 using the Boost theme.

**Comment by m-x-d** [comment]
It works after update, thanks.
There's, however, another issue I've noticed.

In the same conditions (Firefox, Browser security enabled, test launched as a Student), if you drag an answer item away from the items frame and release the mouse, it will still get stuck in the dragged state. Unlike before, you can click to place it back. Doing so adds a text entry cursor to one of the answers, which allows to create new answer items by pressing Enter, or edit answer text by pressing Backspace or arrow keys, then typing. Obviously, you can't actually edit the answers this way, but it still looks kinda wonky...

**Comment by gbateson** [comment]
Oh, that's not very nice.
What gave you the idea to add contenteditable="true?

**Comment by gbateson** [comment]
Ah, I think I see where you found it. In mod/quiz/module.js, right?
In that case, maybe we can leave the UL with contenteditable="true" but set all the child nodes, i.e. LI to contenteditable="false". I'll try that and see how we go ...

**Comment by AntonZab** [comment]
Теперь я понял. Ты мастер удалять сообщения. А на другие поступки ты не способен. А я то думал. Что ты все сможешь. Какой же я дурак. Если одумаешься пиши. Toxazab04@gmail.com А теперь. Извини за беспокойство. Больше не потревожу.

**Comment by m-x-d** [comment]
Seems to be working fine using Moodle 3.6.2+ in Firefox 64.0.2. Thanks!

**Comment by gbateson** [comment]
Thanks for confirming. I will close this issue now, but please reopen it, if the issue occurs again.
