### ISSUE TITLE
Table "qtype_ordering" does not exist

### ISSUE THREAD

**Issue by nachoan** [gbateson/moodle-qtype_ordering#4]
Hi,

I have copied two quizes between two Moodle courses with some qtype_ordering questions. The original one is working properly but the one I have clonned shows me this error.
What ca I do? I have checked my mysql DB  but this table does not exist.

Table "qtype_ordering" does not exist
More information about this error Debug info:
Error code: ddltablenotexist
Stack trace:
    line 1128 of /lib/dml/mysqli_native_moodle_database.php: dml_exception thrown
    line 219 of /question/type/ordering/question.php: call to mysqli_native_moodle_database->insert_record()
    line 58 of /question/type/ordering/question.php: call to qtype_ordering_question->get_ordering_options()
    line 338 of /question/behaviour/behaviourbase.php: call to qtype_ordering_question->start_attempt()
    line 954 of /question/engine/questionattempt.php: call to question_behaviour->init_first_step()
    line 504 of /question/engine/questionusage.php: call to question_attempt->start()
    line 209 of /mod/quiz/locallib.php: call to question_usage_by_activity->start_all_questions()
    line 178 of /mod/quiz/startattempt.php: call to quiz_start_new_attempt()

By the way the Draggable items (Item text) are empty in the quiz copy... Does it make any sense?

Thanks in advance!

I'm using Moodle 2.7.1 and qtype_ordering version 2015013018 (last release)

**Comment by gbateson** [comment]
I guess you are using "two Moodle courses" on **two different Moodle sites**. It seems the destination site does not have the latest version of the Ordering question type. Therefore, please upgrade the Ordering question plugin on the destination site and then try again.

Also, please remove the duplicate report of this issue in your comment on the download page for the Ordering question type on Moodle.org
* https://moodle.org/plugins/view/qtype_ordering

thanks
Gordon

**Comment by nachoan** [comment]
Thanks, your are great!
It solved.
