### ISSUE TITLE
Resuming State 

### ISSUE THREAD

**Issue by M2Roe** [gbateson/moodle-qtype_ordering#41]
We are currently using version 2016102657 on Moodle 3.4. We have an issue where a user returns to an ordering question they have already answered, the quiz does not remember the previous order that the answers were placed in. Is this an issue that has been rectified for the latest version of the plugin?

**Comment by gbateson** [comment]
I believe this issue has been fixed in more recent version of this plugin.
Please update this plugin on your Moodle site andtest the behavior.
Feel free to re-open this issue, if the issue persists.
