### ISSUE TITLE
Duplicate entry error when opening language packs

### ISSUE THREAD

**Issue by jazinheira** [gbateson/moodle-qtype_ordering#43]
Hi,

When opening our language pack for customizing, we're encountering a duplicate entry error for the numberingstyleABC string.

```
Debug info: Duplicate entry 'en_us-478-numberingstyleABC' for key 'mdl_toolcust_lancomstr_uix'
INSERT INTO mdl_tool_customlang (lang,componentid,stringid,original,master,timemodified,outdated,local,timecustomized) VALUES(?,?,?,?,?,?,?,?,?)
[array (
0 => 'en_us',
1 => '478',
2 => 'numberingstyleABC',
3 => 'A., B., C., ...',
4 => 'A., B., C., ...',
5 => 1563974936,
6 => 0,
7 => NULL,
8 => NULL,
)]
Error code: dmlwriteexception 
```

After reading https://moodle.org/mod/forum/discuss.php?d=219504 I think it's due to having both 'numberingstyleABC' and 'numberingstyleabc' lang strings due to case insensitivity.

I also noticed someone else having the same issue - https://moodle.org/mod/forum/discuss.php?d=388624&parent=1566571

**Comment by gbateson** [comment]
Thanks for reporting this issue, jazinheira.
In the latest release of the qtype_ordering plugin, I have fixed this issue by reverting to using "ABCD" and "IIII" for the uppercase versions of the numbering styles. Please update this plugin on your Moodle site(s) and the next convenient opportunity.
