### ISSUE TITLE
Version 2019071292 breaks the ability to customize language strings at the site level

### ISSUE THREAD

**Issue by rolandsherwood2** [gbateson/moodle-qtype_ordering#45]
Hi. Just a quick note to confirm version 2019071292 under Moodle 3.7.1 (stable) appears to break the ability to customise language strings via Site administration > Language > Language customization. After installing version 2019071292, when attempting to customize strings in this way, the following error (with debugging enabled) is presented:

Error writing to database

More information about this error
Debug info: Duplicate entry 'en-487-numberingstyleABC' for key 'mdl_toolcust_lancomstr_uix'
INSERT INTO mdl_tool_customlang (lang,componentid,stringid,original,master,timemodified,outdated,local,timecustomized) VALUES(?,?,?,?,?,?,?,?,?)
[array (
0 => 'en',
1 => '487',
2 => 'numberingstyleABC',
3 => 'A., B., C., ...',
4 => 'A., B., C., ...',
5 => 1564911546,
6 => 0,
7 => NULL,
8 => NULL,
)]
Error code: dmlwriteexception
Stack trace:

    line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
    line 1329 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 1375 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
    line 191 of /admin/tool/customlang/locallib.php: call to mysqli_native_moodle_database->insert_record()
    line 60 of /admin/tool/customlang/index.php: call to tool_customlang_utils::checkout()

After consulting the following page: https://moodle.org/mod/forum/discuss.php?d=219504&parent=1266277 I then queried the database as follows -

SELECT * FROM mdl_tool_customlang_components WHERE id = 487;

The resulting output is:

id | name | version
487 | qtype_ordering | 2019071292

After uninstalling version 2019071292, the error then goes away.

**Comment by sean1746** [comment]
Thanks for reporting this – I experienced this today and reassuring to know I'm not the only one!

**Comment by gbateson** [comment]
This issue was reported in #43 and was subsequently fixed in version 2019073193 [=release 2019-07-31 (93)]
Please update this plugin on your Moodle site at the next convenient opportunity.

**Comment by sean1746** [comment]
Thanks, sorry I hadn't noticed there was an updated version.
