### ISSUE TITLE
The question still seems to not work in Adaptive mode

### ISSUE THREAD

**Issue by dbauer-ets** [gbateson/moodle-qtype_ordering#46]
Hello Gordon,

[Michelle and Joseph reported recently](https://moodle.org/mod/forum/discuss.php?d=391894) that the question was not working in the Adaptive mode. I did a test and it also seems to me that it does not work.

[You mentioned in 2016](https://github.com/gbateson/moodle-qtype_ordering/issues/17) that this issue was solved. Please could you confirm whether it works in Adaptive mode or not.

Best regards.

**Comment by gbateson** [comment]
Hi Dominique,

I appreciate your intervention and clear explanation. Adaptive mode for this plugins certainly *was* working, but since then there have been other contributions to this plugin. It's possible that something has broken along the way. I will investigate.

Kind regards
Gordon

**Comment by gbateson** [comment]
Dominique,
I believe that the latest version, 2019-09-06 (94), of the Ordering question type will fix the issues you found with Adaptive mode.
I would be grateful if you could try out the latest version, and confirm thatit now works as you expect.

Many thanks
Gordon

**Comment by gbateson** [comment]
Thanks for (preliminary) testing of the fix Dominique.
I'll close the github issue now, but feel free to reopen if necessary.
