### ISSUE TITLE
Copying item error

### ISSUE THREAD

**Issue by nachoan** [gbateson/moodle-qtype_ordering#5]
Hello again,

When I use backup items into a course  or sharing chart block for copying quizzes into two courses with qtype_ordering they fail to copy things into database. -> moodle_database::insert_record_raw() no fields found.

Questions are in different categories, but the error it's only with this type of questions, the draggable items are empty inside the copied questions, but not question name and description.

Any help?

-----------------------------------------------------------------------------------------------
Detectado un error de codificación, debe ser corregido por un programador: 
moodle_database::insert_record_raw() no fields found.
Más información sobre este error
Debug info:
Error code: codingerror
Stack trace:

    line 1083 of /lib/dml/mysqli_native_moodle_database.php: coding_exception thrown
    line 1144 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
    line 219 of /question/type/ordering/question.php: call to mysqli_native_moodle_database->insert_record()
    line 58 of /question/type/ordering/question.php: call to qtype_ordering_question->get_ordering_options()
    line 338 of /question/behaviour/behaviourbase.php: call to qtype_ordering_question->start_attempt()
    line 954 of /question/engine/questionattempt.php: call to question_behaviour->init_first_step()
    line 504 of /question/engine/questionusage.php: call to question_attempt->start()
    line 209 of /mod/quiz/locallib.php: call to question_usage_by_activity->start_all_questions()
    line 178 of /mod/quiz/startattempt.php: call to quiz_start_new_attempt()

Output buffer: <div class="alert alert-error">Error: Missing question options!</div><div class="alert alert-error">Error: Missing question options!</div><div class="alert alert-error">Error: Missing question options!</div><br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>927</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>928</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>929</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>931</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>932</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>933</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>927</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>928</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>929</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>931</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>932</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>933</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>927</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>928</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>929</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>931</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>932</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/var/www/lasallepalma/httpdocs/question/type/questiontypebase.php</b> on line <b>933</b><br /> <br /> <b>Notice</b>: Undefined variable: options in <b>/var/www/lasallepalma/httpdocs/question/type/ordering/question.php</b> on line <b>219</b><br /> 

Thanks in advance!

**Comment by gbateson** [comment]
hi Nachoan,
thanks for letting me know about this issue.
Actually, I had the same problem myself a few days ago.
I have fixed an obvious mistake in the code on line 219 of question/type/ordering/question.php.
Please could you try the latest version of this question type, and let me know if it works better for you.
thanks
Gordon

**Comment by gbateson** [comment]
Hi Nachoan,
I took another look at the restore script for the Ordering question type, and realized why the ordering options were not being restored. I have fixed that now and confirmed that the restore of ordering options is now working as expected. Please update the Ordering question type on your Moodle site at the next convenient opportunity.

I will close this issue now, but if you find there is still a problem, please feel free to re-open it and let me know what happened.

best regards
Gordon
