### ISSUE TITLE
Ordering question results in error when trying to make new question or edit an existing question

### ISSUE THREAD

**Issue by easyflhomeschool** [gbateson/moodle-qtype_ordering#62]
Ordering Question worked great until I upgraded to Moodle 11.

http error 5000
Please let me know if there is anything planned for updating this question.   It was just the right format for what I needed.
Thank you

**Comment by gbateson** [comment]
Hi there, I guess you mean Moodle version 3.11.
I have fixed that bug now, so please update this plugin on your Moodle site at the nextx convenient opportunity.
Thanks
