### ISSUE TITLE
generalexceptionmessage saving question in Moodle 3.11

### ISSUE THREAD

**Issue by ksteitz** [gbateson/moodle-qtype_ordering#63]
Using Moodle 3.11 we get a generalexceptionmessage when saving a new question: 
Stack trace: 

    line 406 of /question/type/ordering/edit_ordering_form.php: Error thrown
    line 653 of /lib/formslib.php: call to qtype_ordering_edit_form->validation()
    line 589 of /lib/formslib.php: call to moodleform->validate_defined_fields()
    line 699 of /lib/formslib.php: call to moodleform->is_validated()
    line 232 of /question/question.php: call to moodleform->get_data()

sysinfo:
PHP 7.4
Apache 2.4
PostgreSQL 10

Any ideas or further testin intructions?

Previously created ordering-questions work fine, just saving new ones doen´t work. 

thanks and kind regards
Klaus

**Comment by ewallah** [comment]
In PHPUnit tests, we see an undefined method set_default_value message: 

qtype_ordering_test::test_question_saving (questiontype_test.php:76)
Error: Call to undefined method qtype_ordering_edit_form::set_default_value()
in question/type/ordering/edit_ordering_form.php:406

**Comment by gbateson** [comment]
Thanks ksteitz and ewallah for reporting this issue about the missing method, "set_default_value()".

I have fixed that isue now in the latest release of the plugin: 2021-06-13 (03)

Please update this plugin on your Moodle site at the next convenient opportunity.

Kind regards
Gordon

**Comment by ksteitz** [comment]
Hi Gordon,

thanks for the quick fix, tested successful, works like a charm! :)

kind regards
Klaus
