### ISSUE TITLE
Plugin works with Moodle 4.0

### ISSUE THREAD

**Issue by wanderson-rigo** [gbateson/moodle-qtype_ordering#71]
Hi,

the plugin works fine with Moodle 4.0? When do you will publish updates about this?

**Comment by gbateson** [comment]
Hi Wanderson-Rigo,
the Ordering question type has just  been  updated to work with Moodle 4.x. You  can get the  latest code from github.com. I will publish the latest version to the plugins repository on Moodle .org  very soon.
