### ISSUE TITLE
Unnecessary stripslashes in format_questiontext()?

### ISSUE THREAD

**Issue by joncatalyst** [gbateson/moodle-qtype_ordering#8]
I noticed that there is a local format_questiontext() in question.php. It just calls the parent function, then calls stripslashes() on the returned question text, which results in the backslashes being removed.
Other question-types don't seem to do this, and  backslashes can be useful..
Suggest removing the local function unless there is  good reason for it to be there?

**Comment by gbateson** [comment]
Is the use of backslashes() in question.php causing you problems? Could you provide an example of a question for me to test on?

**Comment by joncatalyst** [comment]
If you set the question text to: 	name 2-1 ctest title [AAA\BBBB]
it is displayed as: name 2-1 ctest title [AAABBBB].
(note that if you do the same in the question title, the backslash is preserved)

**Comment by gbateson** [comment]
Thanks very much for supplying the test case. I have removed the unnecessary call to stripslashes() and confirmed that backslashes in the question text are now preserved. Thanks for bringing this issue to my attention.
