### ISSUE TITLE
Auto refresh after change of editor mode

### ISSUE THREAD

**Issue by Kathrin84** [gbateson/moodle-qtype_ordering#9]
Hi,
in your latest version of your plugin (2015112333), you implemented the possibility to switch between editors or plain text.
When a user chooses for example the html editor, the changes affects the form only after he saved it.
So it would be great if you could add an auto refresh function when selecting another option, so that the chosen editor will load immediately and not only after a save action of the user.

Cheers, Kathrin

**Comment by gbateson** [comment]
I agree. It would be great. I hope I can implement it at some point. thanks for using the Ordering question type. Gordon

**Comment by gbateson** [comment]
Thanks for your feedback Kathrin. I am not likely to implement this functionality soon, but I will keep it on my list of improvements for the Ordering question type.
